# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170221_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Ch_id',
            new_name='ch_id',
        ),
    ]
